# Generated by Django 4.1.5 on 2023-01-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Completed',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
